=== AlbertAlvin8080/Learning_XML/Exercises/ex04_XSD/agenda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agenda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="evento" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="horario" type="xs:time"></xs:element>
                            <xs:element name="titulo" type="xs:string"></xs:element>
                            <xs:element name="local" type="xs:string"></xs:element>
                            <xs:element name="descricao" type="xs:string"></xs:element>
                        </xs:all>
                        <xs:attribute name="data" type="xs:date"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AlbertAlvin8080/Learning_XML/Exercises/ex04_XSD/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="agenda.xsd">
    <evento data="2010-09-23">
        <horario>15:00:00</horario>
        <titulo>Palestra XSD</titulo>
        <descricao>Palestra XSD avançada</descricao>
        <local>Núcleo</local>
    </evento>
    <evento data="2005-12-25">
        <horario>20:30:00</horario>
        <local>UFRJ</local>
        <descricao>Palestra com conceitos e aprofundamentos em xml</descricao>
        <titulo>Palestra XML</titulo>
    </evento>
    <evento data="2019-03-12">
        <horario>03:00:00</horario>
        <titulo>Treino de Bombeiros</titulo>
        <local>Rio Doce</local>
        <descricao>Treinamento matinal de bombeiros</descricao>
    </evento>
</agenda>
